//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallErrorDeshboard.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="templateScheme", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class templateScheme : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                if ((object.ReferenceEquals(this.operationField, value) != true)) {
                    this.operationField = value;
                    this.RaisePropertyChanged("operation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseTemplate", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string htmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HallErrorDeshboard.ServiceReference1.ArrayOfString controlIDsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string html {
            get {
                return this.htmlField;
            }
            set {
                if ((object.ReferenceEquals(this.htmlField, value) != true)) {
                    this.htmlField = value;
                    this.RaisePropertyChanged("html");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public HallErrorDeshboard.ServiceReference1.ArrayOfString controlIDs {
            get {
                return this.controlIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.controlIDsField, value) != true)) {
                    this.controlIDsField = value;
                    this.RaisePropertyChanged("controlIDs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="operationScheme", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class operationScheme : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HallErrorDeshboard.ServiceReference1.ArrayOfString dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HallErrorDeshboard.ServiceReference1.ArrayOfString data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name templateScheme from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulateTemplateView", ReplyAction="*")]
        HallErrorDeshboard.ServiceReference1.PopulateTemplateViewResponse PopulateTemplateView(HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequest request);
        
        // CODEGEN: Generating message contract since element name operationScheme from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        HallErrorDeshboard.ServiceReference1.UpdateDataResponse UpdateData(HallErrorDeshboard.ServiceReference1.UpdateDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PopulateTemplateViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PopulateTemplateView", Namespace="http://tempuri.org/", Order=0)]
        public HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequestBody Body;
        
        public PopulateTemplateViewRequest() {
        }
        
        public PopulateTemplateViewRequest(HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PopulateTemplateViewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HallErrorDeshboard.ServiceReference1.templateScheme templateScheme;
        
        public PopulateTemplateViewRequestBody() {
        }
        
        public PopulateTemplateViewRequestBody(HallErrorDeshboard.ServiceReference1.templateScheme templateScheme) {
            this.templateScheme = templateScheme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PopulateTemplateViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PopulateTemplateViewResponse", Namespace="http://tempuri.org/", Order=0)]
        public HallErrorDeshboard.ServiceReference1.PopulateTemplateViewResponseBody Body;
        
        public PopulateTemplateViewResponse() {
        }
        
        public PopulateTemplateViewResponse(HallErrorDeshboard.ServiceReference1.PopulateTemplateViewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PopulateTemplateViewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HallErrorDeshboard.ServiceReference1.ResponseTemplate PopulateTemplateViewResult;
        
        public PopulateTemplateViewResponseBody() {
        }
        
        public PopulateTemplateViewResponseBody(HallErrorDeshboard.ServiceReference1.ResponseTemplate PopulateTemplateViewResult) {
            this.PopulateTemplateViewResult = PopulateTemplateViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateData", Namespace="http://tempuri.org/", Order=0)]
        public HallErrorDeshboard.ServiceReference1.UpdateDataRequestBody Body;
        
        public UpdateDataRequest() {
        }
        
        public UpdateDataRequest(HallErrorDeshboard.ServiceReference1.UpdateDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HallErrorDeshboard.ServiceReference1.operationScheme operationScheme;
        
        public UpdateDataRequestBody() {
        }
        
        public UpdateDataRequestBody(HallErrorDeshboard.ServiceReference1.operationScheme operationScheme) {
            this.operationScheme = operationScheme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HallErrorDeshboard.ServiceReference1.UpdateDataResponseBody Body;
        
        public UpdateDataResponse() {
        }
        
        public UpdateDataResponse(HallErrorDeshboard.ServiceReference1.UpdateDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateDataResponseBody {
        
        public UpdateDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : HallErrorDeshboard.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<HallErrorDeshboard.ServiceReference1.WebServiceSoap>, HallErrorDeshboard.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HallErrorDeshboard.ServiceReference1.PopulateTemplateViewResponse HallErrorDeshboard.ServiceReference1.WebServiceSoap.PopulateTemplateView(HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequest request) {
            return base.Channel.PopulateTemplateView(request);
        }
        
        public HallErrorDeshboard.ServiceReference1.ResponseTemplate PopulateTemplateView(HallErrorDeshboard.ServiceReference1.templateScheme templateScheme) {
            HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequest inValue = new HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequest();
            inValue.Body = new HallErrorDeshboard.ServiceReference1.PopulateTemplateViewRequestBody();
            inValue.Body.templateScheme = templateScheme;
            HallErrorDeshboard.ServiceReference1.PopulateTemplateViewResponse retVal = ((HallErrorDeshboard.ServiceReference1.WebServiceSoap)(this)).PopulateTemplateView(inValue);
            return retVal.Body.PopulateTemplateViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HallErrorDeshboard.ServiceReference1.UpdateDataResponse HallErrorDeshboard.ServiceReference1.WebServiceSoap.UpdateData(HallErrorDeshboard.ServiceReference1.UpdateDataRequest request) {
            return base.Channel.UpdateData(request);
        }
        
        public void UpdateData(HallErrorDeshboard.ServiceReference1.operationScheme operationScheme) {
            HallErrorDeshboard.ServiceReference1.UpdateDataRequest inValue = new HallErrorDeshboard.ServiceReference1.UpdateDataRequest();
            inValue.Body = new HallErrorDeshboard.ServiceReference1.UpdateDataRequestBody();
            inValue.Body.operationScheme = operationScheme;
            HallErrorDeshboard.ServiceReference1.UpdateDataResponse retVal = ((HallErrorDeshboard.ServiceReference1.WebServiceSoap)(this)).UpdateData(inValue);
        }
    }
}
