//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHelpers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyHelpers.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string DefaultConfiguration {
            get {
                return ResourceManager.GetString("DefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.{0}.QueryBuilder.xml.
        /// </summary>
        internal static string DownloadConfigQueryFile {
            get {
                return ResourceManager.GetString("DownloadConfigQueryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\TemporaryData\FTPDownload.{0}.txt.
        /// </summary>
        internal static string DownloadFilepath {
            get {
                return ResourceManager.GetString("DownloadFilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Rules.EffectiveDate.txt.
        /// </summary>
        internal static string EffectiveDateRule {
            get {
                return ResourceManager.GetString("EffectiveDateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\TemporaryData\Policy.{0}.{1}.{2}.{3}.bin.
        /// </summary>
        internal static string ExceedPolicySerialize {
            get {
                return ResourceManager.GetString("ExceedPolicySerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Temporarydata\ExcelSheet.{0}.xls.
        /// </summary>
        internal static string ExcelFileLocation {
            get {
                return ResourceManager.GetString("ExcelFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Excel.ExcelHeader.txt.
        /// </summary>
        internal static string ExcelFormatterHeader {
            get {
                return ResourceManager.GetString("ExcelFormatterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Rules.ExpirationDate.txt.
        /// </summary>
        internal static string ExpirationDateRule {
            get {
                return ResourceManager.GetString("ExpirationDateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLICYNUMBER.
        /// </summary>
        internal static string LiteralPolicyNumber {
            get {
                return ResourceManager.GetString("LiteralPolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGION.
        /// </summary>
        internal static string LiteralRegion {
            get {
                return ResourceManager.GetString("LiteralRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string MainframeFTPServerPort {
            get {
                return ResourceManager.GetString("MainframeFTPServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 172.27.192.97.
        /// </summary>
        internal static string MainframeFTPServerURL {
            get {
                return ResourceManager.GetString("MainframeFTPServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Rules.MasterCompany.txt.
        /// </summary>
        internal static string MasterCompanyRule {
            get {
                return ResourceManager.GetString("MasterCompanyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.PolicyRelation.txt.
        /// </summary>
        internal static string PolicyRelationFile {
            get {
                return ResourceManager.GetString("PolicyRelationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Exceed.ProductList.txt.
        /// </summary>
        internal static string ProductListFile {
            get {
                return ResourceManager.GetString("ProductListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Rules.Product.txt.
        /// </summary>
        internal static string ProductRule {
            get {
                return ResourceManager.GetString("ProductRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyHelpers.ConfigurationFiles.Rules.Scheme.txt.
        /// </summary>
        internal static string SchemeRule {
            get {
                return ResourceManager.GetString("SchemeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://172.20.192.251/DB2Shadow/DB2ShadowServer.asp.
        /// </summary>
        internal static string ShadowUrl {
            get {
                return ResourceManager.GetString("ShadowUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://172.20.193.100/DB2Shadow/DB2ShadowServer.asp.
        /// </summary>
        internal static string ShadowUrlOld {
            get {
                return ResourceManager.GetString("ShadowUrlOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Temporarydata\SupportDataDownload.{0}.xml.
        /// </summary>
        internal static string SupportDataDownload {
            get {
                return ResourceManager.GetString("SupportDataDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Temporarydata\SupportDataDownload.{0}.final.xml.
        /// </summary>
        internal static string SupportDataUpdates {
            get {
                return ResourceManager.GetString("SupportDataUpdates", resourceCulture);
            }
        }
    }
}
