//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DefectTrackerModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DefectTrackerEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new DefectTrackerEntities object using the connection string found in the 'DefectTrackerEntities' section of the application configuration file.
        /// </summary>
        public DefectTrackerEntities()
            : base("name=DefectTrackerEntities", "DefectTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new DefectTrackerEntities object.
        /// </summary>
        public DefectTrackerEntities(string connectionString)
            : base(connectionString, "DefectTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new DefectTrackerEntities object.
        /// </summary>
        public DefectTrackerEntities(EntityConnection connection)
            : base(connection, "DefectTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MasterError> MasterErrors
        {
            get
            {
                if ((_MasterErrors == null))
                {
                    _MasterErrors = base.CreateObjectSet<MasterError>("MasterErrors");
                }
                return _MasterErrors;
            }
        }
        private ObjectSet<MasterError> _MasterErrors;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the MasterErrors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMasterErrors(MasterError masterError)
        {
            base.AddObject("MasterErrors", masterError);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DefectTrackerModel", Name="MasterError")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MasterError : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MasterError object.
        /// </summary>
        /// <param name="gUID">Initial value of the GUID property.</param>
        public static MasterError CreateMasterError(global::System.Guid gUID)
        {
            MasterError masterError = new MasterError();
            masterError.GUID = gUID;
            return masterError;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReportDate
        {
            get
            {
                return _ReportDate;
            }
            set
            {
                OnReportDateChanging(value);
                ReportPropertyChanging("ReportDate");
                _ReportDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportDate");
                OnReportDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReportDate;
        partial void OnReportDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReportDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorId
        {
            get
            {
                return _ErrorId;
            }
            set
            {
                OnErrorIdChanging(value);
                ReportPropertyChanging("ErrorId");
                _ErrorId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorId");
                OnErrorIdChanged();
            }
        }
        private global::System.String _ErrorId;
        partial void OnErrorIdChanging(global::System.String value);
        partial void OnErrorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorText
        {
            get
            {
                return _ErrorText;
            }
            set
            {
                OnErrorTextChanging(value);
                ReportPropertyChanging("ErrorText");
                _ErrorText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorText");
                OnErrorTextChanged();
            }
        }
        private global::System.String _ErrorText;
        partial void OnErrorTextChanging(global::System.String value);
        partial void OnErrorTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int32> _Count;
        partial void OnCountChanging(Nullable<global::System.Int32> value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusCd
        {
            get
            {
                return _StatusCd;
            }
            set
            {
                OnStatusCdChanging(value);
                ReportPropertyChanging("StatusCd");
                _StatusCd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusCd");
                OnStatusCdChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusCd;
        partial void OnStatusCdChanging(Nullable<global::System.Int32> value);
        partial void OnStatusCdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion
    
    }

    #endregion
    
}
